waikup/views/main.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, flash, redirect, url_for, abort, current_app
from flask.ext.security import login_required, current_user

from waikup.lib.helpers import Paginated
from waikup.models import Link, Category
from waikup.forms import NewLinkForm, ChangePasswordForm, EditLinkForm, SimpleLinkForm, flash_form_errors

main = Blueprint('main', __name__)


def list_links(page_name, links=None):
    toggle_link_id = request.form.get('link_id')
    page_num = request.args.get('page')
    toggle_form = SimpleLinkForm()
    delete_form = SimpleLinkForm()
    if (page_num is None) or (not page_num.isdigit()):
        page_num = 1
    else:
        page_num = int(page_num)
    if toggle_form.validate_on_submit():
        result_ok = Link.toggle_archiving(toggle_link_id)
        if result_ok:
            flash("Toggled archiving for link %s" % toggle_link_id, category="success")
        else:
            flash("Link does not exist: %s" % toggle_link_id, category="danger")
    else:
        flash_form_errors(toggle_form)
    if links is None:
        links = Link.select().where(Link.archived == (page_name == 'archives')).order_by(Link.submitted.desc())
    links = Paginated(links, page_num, current_app.config['ITEMS_PER_PAGE'], links.count())
    return render_template(
        'links_list.html',
        page_name=page_name,
        links=links,
        toggle_form=toggle_form,
        delete_form=delete_form
    )


@main.route('/', methods=['GET', 'POST'])
@login_required
def index():
    return list_links('index')


@main.route('/archives', methods=['GET', 'POST'])
@login_required
def archives():
    return list_links('archives')


@main.route('/newlink', methods=['POST'])
@login_required
def new_link():
    redirect_to = request.args.get('redir', 'index')
    redirect_to = url_for('main.'+redirect_to)
    form = NewLinkForm()
    form.set_category_choices()
    if form.validate_on_submit():
        category = Category.get(Category.name == form.category.data)
        Link.create(
            url=form.url.data,
            title=form.title.data,
            description=form.description.data,
            author=current_user.id,
            category=category
        )
        flash("New link added: %s" % form.url.data, category='success')
        return redirect(redirect_to)
    for field_name, field_errors in form.errors.iteritems():
        for field_error in field_errors:
            flash("%s (field: %s)" % (field_error, field_name), category='error')
    return redirect(redirect_to)


@main.route('/chpasswd', methods=['POST'])
@login_required
def change_password():
    redirect_to = request.args.get('redir', 'index')
    redirect_to = url_for('main.'+redirect_to)
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if not current_user.check_password(form.current.data):
            flash("Wrong password", category='error')
            return redirect(redirect_to)
        current_user.set_password(form.new.data)
        current_user.save()
        flash("Password changed", category='success')
        return redirect(redirect_to)
    for field_name, field_errors in form.errors.iteritems():
        for field_error in field_errors:
            flash("%s (field: %s)" % (field_error, field_name), category='error')
    return redirect(redirect_to)


@main.route('/delete', methods=['POST'])
@login_required
def delete_link():
    redirect_to = request.args.get('redir', 'index')
    redirect_to = url_for('main.'+redirect_to)
    linkid = request.form.get('link_id')
    delete_form = SimpleLinkForm()
    if delete_form.validate_on_submit():
        if linkid is None:
            flash("No link specified", category='error')
            return redirect(redirect_to)
        link = Link.get(Link.id == linkid)
        if link is None:
            flash("Link not found: %s" % linkid, category='error')
            return redirect(redirect_to)
        if (not current_user.is_admin) and (current_user.username != link.author.username):
            flash("You are not allowed to delete this link: %s" % linkid, category='error')
            return redirect(redirect_to)
        link.delete_instance()
        flash("Deleted link: %s" % linkid, category='success')
    else:
        flash_form_errors(delete_form)
    return redirect(redirect_to)


@main.route('/search', methods=['GET'])
@login_required
def search():
    redirect_page = request.args.get('page', 'index')
    page_num = request.args.get('page')
    if (page_num is None) or (not page_num.isdigit()):
        page_num = 1
    else:
        page_num = int(page_num)
    pattern = request.args.get('pattern')
    if pattern is None:
        flash("No pattern given", category='error')
        return list_links(redirect_page)
    archived = redirect_page == 'archives'
    pattern = "%%%s%%" % pattern
    links = Link.select().where(Link.archived == archived).where(
        (Link.title ** pattern) | (Link.description ** pattern)
    )
    links = Paginated(links, page_num, current_app.config['ITEMS_PER_PAGE'], links.count())
    return render_template(
        'links_list.html',
        page_name=redirect_page,
        links=links,
        toggle_form=SimpleLinkForm(),
        delete_form=SimpleLinkForm()
    )


@main.route('/edit_link/<int:linkid>', methods=['GET', 'POST'])
@login_required
def edit_link(linkid):
    form = EditLinkForm()
    form.set_category_choices()
    link = Link.get(Link.id == linkid)
    redirect_page = request.args.get('redir', 'index')
    redirect_to = url_for('main.'+redirect_page)
    if link is None:
        flash("Link not found: %d" % linkid, category='error')
        return redirect(redirect_to)
    if request.method == 'POST':
        if (not current_user.is_admin) and (current_user.username != link.author.username):
            flash("You are not allowed to edit this link: %d" % link.id, category='error')
            return redirect(redirect_to)
        if form.validate_on_submit():
            link.title = form.title.data
            link.url = form.url.data
            link.description = form.description.data
            category = Category.get(Category.name == form.category.data)
            link.category = category
            link.save()
            flash("Updated link: %d" % link.id, category='success')
        else:
            flash_form_errors(form)
        return redirect(redirect_to)
    form.title.data = link.title
    form.url.data = link.url
    form.description.data = link.description
    form.category.data = link.category.name
    return render_template(
        'edit_link_modal_content.html',
        edit_link_form=form,
        link=link,
        page_name=redirect_page
    )


# @main.route('/stats')
# @login_required
# def stats():
#     return render_template(
#         'stats.html',
#         page_name="stats"
#     )

waikup/templates/base.html
{% extends "bootstrap/base.html" %}
{% from "bootstrap/utils.html" import flashed_messages %}

{%- block head -%}
  {{ super() }}
  <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" />
{%- endblock -%}

{%- block meta -%}
  {{ super() }}
  <meta name="description" content="Collaborative news sharing platform">
  <meta name="keywords" content="RSS,Atom,feeds,collaboration">
  <meta name="author" content="Mathieu D. (MatToufoutu)">
  <meta name="copyright" content="Mathieu D. (MatToufoutu)">
  <meta name="HandheldFriendly" content="True">
  <meta name="charset" content="UTF-8">
{%- endblock -%}

{%- block styles -%}
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('static', filename="css/waikup.css") }}" />
{%- endblock -%}

{%- block navbar -%}
  {% include "header.html" %}
{%- endblock -%}

{%- block content -%}
  {% include 'new_link_modal.html' %}
  {% include 'change_passwd.html' %}
  {% include 'user_profile.html' %}
  {{ flashed_messages(dismissible=True) }}
  <div class="container">
    {% block container -%}{%- endblock %}
  </div>
{%- endblock -%}

{%- block scripts -%}
  {{ super() }}
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.5.10/clipboard.min.js"></script>
  <script type="text/javascript" src="{{ url_for('static', filename="js/waikup.js") }}"></script>
{%- endblock -%}

waikup/templates/change_passwd.html
{% from "bootstrap/wtf.html" import quick_form %}

{% if current_user.is_authenticated %}
  <div class="modal fade"
       id="chpasswd-modal"
       tabindex="-1"
       role="dialog"
       aria-labelledby="chpasswd-modal-label"
       aria-hidden="true"
      >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="chpasswd-modal-label">Change password</h4>
        </div>
        <!-- /.modal-header -->
        <div class="modal-body">
          {{ quick_form(chpasswd_form,
                        form_type='horizontal',
                        action=url_for(chpasswd_form.endpoint),
                        id=chpasswd_form.name+'-form'
          ) }}
        </div>
        <!-- /.modal-body -->
        <div class="modal-footer">
          <button class="btn btn-success" id="chpasswd-save">
            <span class="glyphicon glyphicon-ok-circle"></span> Save
          </button>
          <button class="btn btn-danger" data-dismiss="modal" id="chpasswd-cancel">
            <span class="glyphicon glyphicon-remove-circle"></span> Cancel
          </button>
        </div>
        <!-- /.modal-footer -->
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div><!-- /.modal.fade -->
{% endif %}

waikup/templates/edit_link_modal_content.html
{% from "bootstrap/wtf.html" import quick_form %}

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h4 class="modal-title" id="link-modal-label">{{ link.title }}</h4>
</div>
<div class="modal-body">
  {{ quick_form(edit_link_form,
                form_type='horizontal',
                id=edit_link_form.name + '-form-' + (link.id|string),
                action=url_for(edit_link_form.endpoint, linkid=link.id, redir=page_name)
  ) }}
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal" id="edit-link-cancel-{{ link.id }}">Cancel</button>
  <button type="button" class="btn btn-primary" id="edit-link-save-{{ link.id }}">Save changes</button>
</div>1

waikup/templates/header.html
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-bar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">WaikUp</div>
    </div>
    <!-- /.navbar-header -->
    <div class="navbar-collapse collapse" id="nav-bar">
      {% if current_user.is_authenticated %}
        <ul class="nav navbar-nav">
          <li class="nav-divider"></li>
          <li{% if page_name == 'index' %} class="active"{% endif %}><a href="{{ url_for('main.index') }}">
            <span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Links
          </a></li>
          <li{% if page_name == 'archives' %} class="active"{% endif %}><a href="{{ url_for('main.archives') }}">
            <span class="glyphicon glyphicon-folder-close"></span>&nbsp;&nbsp;Archives
          </a></li>
          <li class="nav-divider"></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-user"></span>
              &nbsp;&nbsp;{{ current_user.first_name }} {{ current_user.last_name }}&nbsp;<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><a href="#" data-toggle="modal" data-target="#profile-modal">
                <span class="glyphicon glyphicon-cog"></span> Profile
              </a></li>
              <li><a href="#" data-toggle="modal" data-target="#chpasswd-modal">
                <span class="glyphicon glyphicon-lock"></span> Change password
              </a></li>
              {% if current_user.is_admin %}
                <li><a href="{{ url_for('admin.index') }}">
                  <span class="glyphicon glyphicon-flash"></span> Administration
                </a></li>
              {% endif %}
              <li class="divider"></li>
              <li><a href="{{ url_for('security.logout') }}">
                <span class="glyphicon glyphicon-off"></span> Logout
              </a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-right">
          <button class="btn btn-primary"
                  type="button"
                  data-toggle="modal"
                  data-target="#new-link-modal"
              >
            <span class="glyphicon glyphicon-link"></span>&nbsp;&nbsp;Submit link
          </button>
        </form>
        <form action="{{ url_for('main.search') }}" class="navbar-form navbar-right" method="get">
          <div class="form-group">
            <input class="form-control" type="text" name="pattern"/>
            <input type="hidden" name="page" value="{{ page_name }}"/>
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>
      {% endif %}
    </div>
    <!-- /.navbar-collapse.collapse -->
  </div>
  <!-- /.container -->
</div><!-- /.navbar.navbar-inverse.navbar-fixed-top -->

waikup/templates/links_list.html
{% extends "base.html" %}

{% block title %}{{ page_name|title }}{% endblock %}

{% block container %}
  &nbsp;<a href="#" title="expand all"><span class="glyphicon glyphicon-zoom-in expand-all"></span></a>
  &nbsp;<a href="#" title="collapse all"><span class="glyphicon glyphicon-zoom-out collapse-all"></span></a>
  <div class="table-responsive">
  <table id="links-list" class="table table-hover table-bordered">
    <thead>
    <tr>
      <th>Link</th>
      <th>Category</th>
      <th>Submission date</th>
      <th>Submitter</th>
    </tr>
    </thead>
    <tbody>
    {% for link in links %}
      <tr>
        <td>
          <a id="link{{ link.id }}"
             class="collapser btn btn-default btn-xs link-action"
             data-toggle="collapse"
             data-target="link{{ link.id }}"
             href="#"
             title="show description">
            <span class="glyphicon glyphicon-eye-open"></span>
          </a>&nbsp;
          <a class="toggle-archive link-post-action btn btn-default btn-xs link-action"
             id="toggle-link-{{ link.id }}"
             href="#"
             title="toggle archiving">
            {% if page_name == 'index' %}
              <span class="glyphicon glyphicon-folder-close"></span>
            {% else %}
              <span class="glyphicon glyphicon-folder-open"></span>
            {% endif %}
          </a>&nbsp;
          <form class="hidden" method="POST"
                id="toggle-form-{{ link.id }}"
                action="{{ url_for('main.'+page_name) }}">
            {{ delete_form.csrf_token() }}
            {{ delete_form.link_id(value=link.id) }}
          </form>
          {% if current_user.is_admin or link.author.username == current_user.username %}
            <a data-toggle="modal"
               class="btn btn-default btn-xs link-action"
               data-target="#edit-link-modal-{{ link.id }}"
               href="{{ url_for('main.edit_link', linkid=link.id, redir=page_name) }}"
               title="edit link">
              <span class="glyphicon glyphicon-pencil"></span>
            </a>&nbsp;
            <a href="#"
               class="delete-link link-post-action btn btn-danger btn-xs link-action"
               id="delete-link-{{ link.id }}"
               title="delete">
              <span class="glyphicon glyphicon-trash"></span>
            </a>&nbsp;
            <form class="hidden" method="POST"
                  id="delete-form-{{ link.id }}"
                  action="{{ url_for('main.delete_link', redir=page_name, linkid=link.id) }}">
              {{ delete_form.csrf_token() }}
              {{ delete_form.link_id(value=link.id) }}
            </form>
          {% endif %}
          &nbsp;&nbsp;<a href="{{ link.url }}" target="_blank">{{ link.title }}
        </a></td>
        <td>{{ link.category.name }}</td>
        <td>{{ link.submitted.strftime(config.DATETIME_FORMAT) }}</td>
        <td>{{ link.author.full_name }}</td>
      </tr>
      <tr>
        <td id="collapsible-td" colspan="4">
          <div class="collapse out" id="link{{ link.id }}">{{ link.description }}</div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  </div>
  {% if links.pages > 1 %}
    <div class="row col-md-4 col-md-offset-4">
      <ul class="pagination" style="text-align: center">
        {% set previous = links.page - 1 %}
        {% set next = links.page + 1 %}
        <li{% if not links.has_previous %} class="disabled"{% endif %}><a
            href="{{ url_for('main.'+page_name, page=previous) }}"><strong>&laquo;</strong></a></li>
        <li class="disabled "><a href="#">{{ links.page }} / {{ links.pages }}</a></li>
        <li{% if not links.has_next %} class="disabled" {% endif %}><a
            href="{{ url_for('main.'+page_name, page=next) }}"><strong>&raquo;</strong></a></li>
      </ul>
    </div>
  {% endif %}
  {% for link in links %}
    <div class="modal fade edit-link-modal"
         id="edit-link-modal-{{ link.id }}"
         tabindex="-1"
         role="dialog"
         aria-labelledby="link-modal-label"
         aria-hidden="true">
      <div class="modal-dialog" id="edit-link-dialog-{{ link.id }}">
        <div class="modal-content">
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}

waikup/templates/new_link_modal.html
{% from "bootstrap/wtf.html" import quick_form %}

{% if current_user.is_authenticated %}
  <div class="modal fade"
       id="new-link-modal"
       tabindex="-1"
       role="dialog"
       aria-labelledby="new-link-modal-label"
       aria-hidden="true"
      >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="new-link-modal-label">Submit link</h4>
        </div>
        <!-- /.modal-header -->
        <div class="modal-body">
          {{ quick_form(new_link_form, form_type='horizontal', id='new-link-form', action=url_for(new_link_form.endpoint)) }}
        </div>
        <!-- /.modal-body -->
        <div class="modal-footer">
          <button class="btn btn-success" id="new-link-save">
            <span class="glyphicon glyphicon-ok-circle"></span> Save
          </button>
          <button class="btn btn-danger" data-dismiss="modal" id="new-link-cancel">
            <span class="glyphicon glyphicon-remove-circle"></span> Cancel
          </button>
        </div>
        <!-- /.modal-footer -->
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div><!-- /.modal.fade -->
{% endif %}

waikup/templates/stats.html
{% extends 'base.html' %}
{% block title %}{{ page_name|title }}{% endblock %}
{% block scripts %}
  {{ super() }}
  <script type="text/javascript" src="{{ url_for('static', filename="js/Chart.min.js") }}"></script>
  <script type="text/javascript">
    var chartHeight = window.innerHeight - (window.innerHeight * 50 / 100);
    var chartWidth = window.innerWidth - (window.innerWidth * 20 / 100);
    $('canvas').attr('height', chartHeight + 'px').attr('width', chartWidth + 'px');
    function createBarChart(canvasID) {
      function innerCreateBarChart(data) {
        var ctx = document.getElementById(canvasID).getContext('2d');
        var chartData = {
          labels: [],
          datasets: [
            {
              fillColor: "rgba(220,220,220,0.5)",
              strokeColor: "rgba(220,220,220,1)",
              data: []
            }
          ]
        };
        var submitters = (typeof data['submitters'] === "undefined") ? [] : data['submitters'];
        for (var i = 0; i <= submitters.length - 1; i++) {
          var value = submitters[i];
          chartData.labels.push(value[0] + ' (' + value[1] + ')');
          chartData.datasets[0].data.push(value[1]);
        }
        new Chart(ctx).Bar(chartData);
      }

      return innerCreateBarChart;
    }
    api = WaikUp('/api', '{{ internal_api_token }}');
    api.topFiveSubmitters(createBarChart("top-five-submitters"));
  </script>
{% endblock %}
{% block content %}
  <h3>Top 5 submitters</h3>
  <canvas id="top-five-submitters" width="0px" height="0px"></canvas>
  <canvas id="top-five-submitters" width="0px" height="0px"></canvas>
{% endblock %}

waikup/templates/user_profile.html
{% if current_user.is_authenticated %}
  <div class="modal fade"
       id="profile-modal"
       tabindex="-1"
       role="dialog"
       aria-labelledby="profile-modal-label"
       aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="profile-modal-label">Your profile</h4>
        </div>
        <!-- /.modal-header -->
        <div class="modal-body">
          <table class="table table-hover table-responsive" id="user-profile">
            <tbody>
            <tr>
              <td><strong>Username:</strong></td>
              <td>{{ current_user.username }}</td>
            </tr>
            <tr>
              <td><strong>First name:</strong></td>
              <td>{{ current_user.first_name }}</td>
            </tr>
            <tr>
              <td><strong>Last name:</strong></td>
              <td>{{ current_user.last_name }}</td>
            </tr>
            <tr>
              <td><strong>Email:</strong></td>
              <td>{{ current_user.email }}</td>
            </tr>
            <tr>
              <td><strong>Admin:</strong></td>
              <td>{% if current_user.is_admin %}Yes{% else %}No{% endif %}</td>
            </tr>
            <tr>
              <td><strong>API Key</strong></td>
              <td>
                {{ current_user.get_auth_token() }}&nbsp;
                <button
                    class="btn btn-default" data-clipboard-text="{{ current_user.get_auth_token() }}"
                    data-toggle="tooltip"
                    data-placement="bottom"
                    title="Copy to clipboard"
                    data-clipboard-btn>
                  <span class="glyphicon glyphicon-copy"></span>
                </button>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
        <!-- /.modal-body -->
        <div class="modal-footer">
          <button class="btn btn-default" data-dismiss="modal">
            <span class="glyphicon glyphicon-remove-circle"></span> Close
          </button>
        </div>
        <!-- /.modal-footer -->
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div><!-- /.modal.fade -->
{% endif %}